In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install -U ultralytics

Collecting ultralytics
  Downloading ultralytics-8.3.246-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.3.246-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 59.9 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.3.246 ultralytics-thop-2.0.18

In [3]:
from ultralytics.utils.benchmarks import benchmark

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [4]:
import ultralytics
ultralytics.checks()

Ultralytics 8.3.246 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 38.5/112.6 GB disk)

In [5]:
import shutil
from pathlib import Path
import os
import yaml

# Przygotowanie danych

In [6]:
zip_path = "/content/drive/MyDrive/dane_detekcja_pojazdow/EAGLE_dataset_1024_res_cleaned_obb.zip" #mniejszy zbiór

!cp "{zip_path}" /content/

In [7]:
!unzip -q /content/EAGLE_dataset_1024_res_cleaned_obb.zip -d /content/data

In [8]:
data_path = Path("/content/data/content/data_1024_res")
yaml_file_path = data_path / "data.yaml"

In [9]:
data_content = {
    'path': '../EagleDatasetYOLO',
    'train': 'images/train',
    'val': 'images/val',
    'test': 'images/test',
    'nc': 1,
    'names': ['vehicle']
}

with open(yaml_file_path, 'w') as f:
    yaml.dump(data_content, f, default_flow_style=False)

print(f"YAML file created at: {yaml_file_path}")
print("Content:")
print(yaml.dump(data_content, indent=2))

YAML file created at: /content/data/content/data_1024_res/data.yaml
Content:
names:
- vehicle
nc: 1
path: ../EagleDatasetYOLO
test: images/test
train: images/train
val: images/val

In [10]:
with open(yaml_file_path, 'r') as f:
    yaml_content = yaml.safe_load(f)

print(yaml.dump(yaml_content, indent=2))

names:
- vehicle
nc: 1
path: ../EagleDatasetYOLO
test: images/test
train: images/train
val: images/val

In [11]:
# Assuming data_path and yaml_file_path are already defined
# (based on previous notebook state)

# Ensure data_path is a string for the YAML content
updated_data_path_str = str(data_path)

# Update the 'path' attribute in the loaded YAML content
yaml_content['path'] = updated_data_path_str

# Save the updated YAML content back to the file
with open(yaml_file_path, 'w') as f:
    yaml.dump(yaml_content, f)

print(f"'path' attribute in {yaml_file_path} updated to: {yaml_content['path']}")

# Display the updated YAML content to verify
print("\nUpdated YAML content:")
print(yaml.dump(yaml_content, indent=2))

'path' attribute in /content/data/content/data_1024_res/data.yaml updated to: /content/data/content/data_1024_res

Updated YAML content:
names:
- vehicle
nc: 1
path: /content/data/content/data_1024_res
test: images/test
train: images/train
val: images/val

# Wykonanie benchmarków

In [12]:
# wykonanie benchamrku
model_path = '/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt'

## TensorRT

### half=false

In [13]:
benchmark(
    model = model_path,
    data = yaml_file_path,
    imgsz=1024,
    device=0,
    half=False,
    format='engine'
)

Setup complete ✅ (2 CPUs, 12.7 GB RAM, 55.0/112.6 GB disk)

Benchmarks complete for /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt on /content/data/content/data_1024_res/data.yaml at imgsz=1024 (297.15s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+---------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+=============================================================================================+
| 1   TensorRT   ✅         14.8        0.7754                8.17                     122.43 |
+---------------------------------------------------------------------------------------------+

+---------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+=============================================================================================+
| 1   TensorRT   ✅         14.8        0.7754                8.17                     122.43 |
+---------------------------------------------------------------------------------------------+

### half=true

In [14]:
benchmark(
    model = model_path,
    data = yaml_file_path,
    imgsz=1024,
    device=0,
    half=True,
    format='engine'
)

Setup complete ✅ (2 CPUs, 12.7 GB RAM, 55.1/112.6 GB disk)

Benchmarks complete for /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt on /content/data/content/data_1024_res/data.yaml at imgsz=1024 (419.14s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+--------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS   |
+============================================================================================+
| 1   TensorRT   ✅         7.5         0.7746                6.79                     147.3 |
+--------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS   |
+============================================================================================+
| 1   TensorRT   ✅         7.5         0.7746                6.79                     147.3 |
+--------------------------------------------------------------------------------------------+

### int8

In [17]:
benchmark(
    model = model_path,
    data = yaml_file_path,
    imgsz=1024,
    device=0,
    int8=True,
    format='engine'
)

Setup complete ✅ (2 CPUs, 12.7 GB RAM, 55.2/112.6 GB disk)

Benchmarks complete for /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt on /content/data/content/data_1024_res/data.yaml at imgsz=1024 (1001.77s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+---------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+=============================================================================================+
| 1   TensorRT   ✅         6.0         0.7508                5.88                     170.18 |
+---------------------------------------------------------------------------------------------+

+---------------------------------------------------------------------------------------------+
|     Format     Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+=============================================================================================+
| 1   TensorRT   ✅         6.0         0.7508                5.88                     170.18 |
+---------------------------------------------------------------------------------------------+

## Zbiorczy benchmark

In [18]:
benchmark(
    model=model_path,
    data=yaml_file_path,
    imgsz=1024,
    half=True,           # Zostawiamy dla porównania
    device=0,
)

Setup complete ✅ (2 CPUs, 12.7 GB RAM, 55.6/112.6 GB disk)

Benchmarks complete for /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt on /content/data/content/data_1024_res/data.yaml at imgsz=1024 (2171.18s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         5.7         0.7871                25.19                    39.69  |
| 2    TorchScript             ✅         5.7         0.7746                12.82                    78.01  |
| 3    ONNX                    ✅         5.3         0.7746                18.05                    55.39  |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         7.4         0.7746                7.02                     142.41 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ❌         0.0         -                     -                        -      |
| 8    TensorFlow GraphDef     ❌         0.0         -                     -                        -      |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         5.3         0.7754                445.01                   2.25   |
| 14   NCNN                    ✅         5.4         0.7754                391.2                    2.56   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera                 ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         5.7         0.7871                25.19                    39.69  |
| 2    TorchScript             ✅         5.7         0.7746                12.82                    78.01  |
| 3    ONNX                    ✅         5.3         0.7746                18.05                    55.39  |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         7.4         0.7746                7.02                     142.41 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ❌         0.0         -                     -                        -      |
| 8    TensorFlow GraphDef     ❌         0.0         -                     -                        -      |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         5.3         0.7754                445.01                   2.25   |
| 14   NCNN                    ✅         5.4         0.7754                391.2                    2.56   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera                 ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

# Eksport do wybranego formatu

In [14]:
from ultralytics import YOLO

model = YOLO(model_path)

model.export(
    format='engine',
    imgsz=1024,
    half=True,
    device=0,
    workspace=4,
    simplify=True,
    data=yaml_file_path
)

Ultralytics 8.3.246 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
💡 ProTip: Export to OpenVINO format for best performance on Intel hardware. Learn more at https://docs.ultralytics.com/integrations/openvino/
YOLO11n-obb summary (fused): 109 layers, 2,653,918 parameters, 0 gradients, 6.6 GFLOPs

PyTorch: starting from '/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.pt' with input shape (1, 3, 1024, 1024) BCHW and output shape(s) (1, 6, 21504) (5.7 MB)
requirements: Ultralytics requirements ['onnx>=1.12.0,<2.0.0', 'onnxslim>=0.1.71', 'onnxruntime-gpu'] not found, attempting AutoUpdate...
Using Python 3.12.12 environment at: /usr
Resolved 14 packages in 421ms
Prepared 6 packages in 6.03s
Installed 6 packages in 386ms
 + colorama==0.4.6
 + coloredlogs==15.0.1
 + humanfriendly==10.0
 + onnx==1.20.0
 + onnxruntime-gpu==1.23.2
 + onnxslim==0.1.82

requirements: AutoUpdate success ✅ 7.5s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.20.0 opset 20...
ONNX: slimming with onnxslim 0.1.82...
ONNX: export success ✅ 11.5s, saved as '/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.onnx' (10.5 MB)
requirements: Ultralytics requirement ['tensorrt-cu12>7.0.0,!=10.1.0'] not found, attempting AutoUpdate...
Using Python 3.12.12 environment at: /usr
Resolved 5 packages in 59.58s
Prepared 4 packages in 1m 21s
Uninstalled 1 package in 6ms
Installed 4 packages in 8ms
 - nvidia-cuda-runtime-cu12==12.6.77
 + nvidia-cuda-runtime-cu12==12.9.79
 + tensorrt-cu12==10.14.1.48.post1
 + tensorrt-cu12-bindings==10.14.1.48.post1
 + tensorrt-cu12-libs==10.14.1.48.post1

requirements: AutoUpdate success ✅ 141.9s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


TensorRT: starting export with TensorRT 10.14.1.48.post1...
TensorRT: input "images" with shape(1, 3, 1024, 1024) DataType.FLOAT
TensorRT: output "output0" with shape(1, 6, 21504) DataType.FLOAT
TensorRT: building FP16 engine as /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.engine
TensorRT: export success ✅ 530.2s, saved as '/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.engine' (7.7 MB)

Export complete (532.3s)
Results saved to /content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights
Predict:         yolo predict task=obb model=/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.engine imgsz=1024 half
Validate:        yolo val task=obb model=/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.engine imgsz=1024 data=/content/data/content/data_1024_res/data.yaml half
Visualize:       https://netron.app

'/content/drive/MyDrive/YOLO_Project/test_scale_1_0/weights/best.engine'